name: CI

on:
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install dependencies
      run: |
        npm install -g npm@latest
        npm install

    - name: Build
      run: npm run build

    - name: Run tests
      run: npm test -- --passWithNoTests

    - name: Check test status
      if: failure()
      run: |
        echo "Tests failed. This PR cannot be merged until all tests pass."
        exit 1 