name: CI

on:
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Check if only non-test files changed
      id: check_changes
      run: |
        git fetch origin main
        CHANGED_FILES=$(git diff --name-only ${{ github.event.pull_request.base.sha }})
        echo "Changed files:"
        echo "$CHANGED_FILES"
        if echo "$CHANGED_FILES" | grep -E "^(src/components/|src/utils/|src/hooks/|src/context/|src/pages/|src/App\.tsx|src/index\.tsx)"; then
          echo "Found changes in test-required files"
          echo "changes=true" >> $GITHUB_OUTPUT
        else
          echo "No changes in test-required files"
          echo "changes=false" >> $GITHUB_OUTPUT
        fi

    - name: Setup Node.js
      if: steps.check_changes.outputs.changes == 'true'
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install pnpm
      if: steps.check_changes.outputs.changes == 'true'
      uses: pnpm/action-setup@v2
      with:
        version: 8

    - name: Install dependencies
      if: steps.check_changes.outputs.changes == 'true'
      run: pnpm install

    - name: Build
      if: steps.check_changes.outputs.changes == 'true'
      run: pnpm build

    - name: Run tests
      if: steps.check_changes.outputs.changes == 'true'
      run: pnpm test -- --passWithNoTests

    - name: Check test status
      if: steps.check_changes.outputs.changes == 'true' && failure()
      run: |
        echo "Tests failed. This PR cannot be merged until all tests pass."
        exit 1 